### ISSUE TITLE
[BUG] A way of glitching out the hint function

### ISSUE THREAD

**Issue by memorylick** [state-of-the-art/matrix-midi-controller#11]
If the menu is exited (by either of 2 currently existing ways) before you completely let go of a hint-triggering button, the hint will keep scrolling by itself forever in both "play" and "menu" modes (the area it takes over remains "playable" tho). Re-triggering any hint by pressing any button in the menu returns things to normal.

**Comment by state-of-the-art** [comment]
Reproduced, confirmed.

**Comment by memorylick** [comment]
Fixed.

**Comment by state-of-the-art** [comment]
Until it's merged - it's not.

**Comment by memorylick** [comment]
The fix has been merged with the master and tested
