### ISSUE TITLE
[FEATURE] Pitch Wheel

### ISSUE THREAD

**Issue by memorylick** [state-of-the-art/matrix-midi-controller#2]
Add two buttons to the "play" mode imitating a pitch wheel. Don't think about the smoothness of the wheel's movement for now: synths will figure it out themselves, it's gonna work fine.
- Realization proposal 1:
   - Make the upper left button a blue or green "pitch down" one, sending "pitch bend -64" (minimum) message on hold, and "pitch bend 0" on release.
   - To the right of the "pitch down" make a red "pitch up" button that sends "pitch bend 63" (maximum) message on hold, and "pitch bend 0" on release.
  - Add a switch button to the menu mode allowing to turn on/off the appearance of the "pitch wheel".
 - Realization proposal 2:
Alternatively, I think a 2-step pitch mode would also be very useful (that way in the menu you could switch between pitch mode 1, pitch mode 2, and the off mode.
So, instead of just 2 buttons next to each other (up and down) there could be 4 buttons: 1234
   - red, pitch bend -64 (0 on release)
   - blue/green, pitch bend -32 (0 on release)
   - blue/green, pitch bend 32 (0 on release)
   - red, pitch bend 63 (0 on release)

**Comment by state-of-the-art** [comment]
I think it will be better to use the second proposal - since full pitch is a tone and we need a way to choose half tone or tone pitch.

**Comment by memorylick** [comment]
Basic pitch wheel emulation has been implemented and works fine. Yay!

An improvement over its current operation has been submitted as a separate [feature](https://github.com/state-of-the-art/matrix-midi-controller/issues/14)
